### ISSUE TITLE
Support inherit value for color prop in `TextBox`

### ISSUE THREAD

**Issue by doniyor2109** [superdispatch/web-ui#187]
Sometimes when `TextBox` component is used with composition with different parent components. For example with `Tag` component and parent components sets some predefined colors for children component. However `TextBox` does not support those colors from parents. It always sets default value.

**Current behavior**
`TextBox` supports only custom colors like `grey`, `white` and etc.

**Expected behavior**
`TextBox` should also supports `inherit` value for `color` prop.

**Comment by devdesrel** [comment]
> @devdesrel Do you wanna take a shot?

@doniyor2109  yess

**Comment by doniyor2109** [comment]
Fixed in #247
